name: CI and CT (Data Flow Coverage)
run-name: ${{ github.actor }} has triggered the workflow

# set up the action on push and pull_request in the master branch
on: 
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
# define jobs
jobs:
  Ba-dua-report-generation:
  
    # Linux-like test env
    runs-on: ubuntu-latest
    steps:
      # checkout repository
      - name: Check out repository
        uses: actions/checkout@v3
      
      # set up JDK 
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      
      # maven cache
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      # build, run tests and generate Ba-dua report
      - name: Build, run tests and generate Ba-dua rport
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: mvn clean verify -P Data-flow-Coverage
    
      # upload the report as artifact
      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: report-ba-dua-bookkeeper-server
          path: bookkeeper-server/target/badua-report.xml
          if-no-files-found: error
