name: CI and CT (Mutation Testing)
run-name: ${{ github.actor }} has triggered the workflow

# set up the action on push and pull_request in the master branch
on: 
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
# define jobs
jobs:
  Build-and-run-tests:
  
    # Linux-like test env
    runs-on: ubuntu-latest
    steps:
      # checkout repository
      - name: Check out repository
        uses: actions/checkout@v3
      
      # set up JDK 
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      
      # maven cache
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      # build and run tests with mutation testing
      - name: Build and run tests with mutation testing
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: mvn clean verify -P Mutation-testing
    
      # upload the report as artifact
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: report-mutation-testing-bookkeeper-server
          path: bookkeeper-server/target/pit-reports
          if-no-files-found: error
